### ISSUE TITLE
 using operator-courier which is no longer maintained and supported 

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/operator-test-playbooks#296]
**Description**

This project has been using operator-courier as described in this readme. See: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/search?q=operator-courier

operator-courier is no longer maintained and supported for a while. 

A pushed a PR to clarify it on the project, see: https://github.com/operator-framework/operator-courier/pull/207

However, it also seems that we ought to change this playbook to use SDK instead.

**Comment by camilamacedo86** [comment]
c/c @dirgim , @mvalarh, @J0zi

**Comment by lslebodn** [comment]
@camilamacedo86  this repository is used 2 independent use-cases.
* downstream (RH)
* upstream

operator-courier was already removed from usptream.

However nobody told us we can drop support for metadata in downstream.
There were discussion in past and it was mentioned there might be very rare cases where operator metadata might still need to be somehow release. And therefore at leas minimal testing should be done by CVP.

We can remove operator-courier when somebody will tell us that support for old format should be dropped.
Which might be tight to removing support for such builds in koji.

**Comment by camilamacedo86** [comment]
HI @lslebodn, 

All tests checks were moved out to operator-framework/API. I tried to clarify it in operator-framework/operator-courier#207 . 

> There were discussion in past and it was mentioned there might be very rare cases where operator metadata might still need to be somehow released. And therefore at least minimal testing should be done by CVP.

So, I cannot see a scenario where that ought to be tested. Could you please find an example and let us know what test or checked still missing to be ported to operator-framework/API? 

Note that the project has not been updated for too long and any new check, warning or fix is pushed against operator-framework/API. So, are the operator-test-playbooks testing all that should really be tested? 

> We can remove operator-courier when somebody will tell us that support for old format should be dropped.
Which might be tight to removing support for such builds in koji.

Community pipeline converts the packagemanifest to bundle format and do the tests using OPM. 
SDK also provides a command for that https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/osdk-pkgman-to-bundle.html.

Could not the playbooks do the same to run the tests?

**Comment by dirgim** [comment]
I agree with @lslebodn - porting the legacy processes to use the new tooling wouldn't make sense at this point as we're expecting to mothball the old pipeline soon in any case.

**Comment by camilamacedo86** [comment]
Hi @lslebodn, 

> There is not any benefit to do any changes to old style metadata testing

Could you please clarify what do you mean by it?
What do you call as` old style metadata testing`? 

> The only reasonable change would be drop support and to completely remove all unused & legacy code.

What would you like to drop the support? Could you please clarify? 
 
> porting the legacy processes to use the new tooling wouldn't make sense at this point as we're expecting to 
mothball the old pipeline soon in any case.

We will no longer use this project or the ansible playbooks where the operator-courier is called? is that what you are trying to share?

**Comment by camilamacedo86** [comment]
Hi @lslebodn and @dirgim,

Thank you for the clarifications.
Just for we register here: The playbooks which are still using the operator-courier are no longer used for OCP version 4.6+. 

So, that is totally fine and I agree we can close this one. 
Again, thank you for the clarification 🥇
